---
title: "Check-in and Progress Check 1"
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
format:
  clean-revealjs:
    self-contained: true
    chalkboard: false
    standalone: true
    slide-number: true
code-annotations: hover
bibliography: QMLS_Bibliography.bib
csl: evolution.csl
---


# Check-in {background-color="#40666e"}


## Impressions

- Pacing
    - Mostly just right, some too fast
- Difficulty
    - Mostly just right, some too challenging


## Themes

- Programming is challenging
    - Practice, think about what you have learned so far
- Work in class is comfortable, work outside of class is difficult
    - It will get better
    - Ask us for help
- More
    - In-class coding
    - Explaining R code
    - Repeated examples (up to a point)


# Questions {background-color="#f8c471"}


# Progress check {background-color="#40666e"}


## General guidelines

- Work on your own
    - Challenge of working alone
    - Clear picture of where you are
- Use all your problem sets, lecture slide code, etc.
- Ask us for help


## Today

- Problem set 4, question 1 (correlation)
- Finish lecture material (regression)
- Back to PS 4
- Stop and review the pipe: `|>`


## Tuesday in class

- Discussion questions due *Monday night*
    - General review topics
- Review / discussion / questions
- Intro to micropublication project
- Progress check available
- Start working


## Thursday in class

- PS 4 is due (but try to finish earlier)
- (More) discussion questions due *Wednesday night*
- Review / discussion / questions
- Continue working
- Due the *following* Thursday (2/26)


# Questions {background-color="#f8c471"}
